{% set name = "QScreenCast" %}
{% set version = "0.1.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QScreenCast-{{ version }}.tar.gz
  sha256: e2dbd5b4cf3a5acad92e790e92dc23b88a46b4b30aacaa87e8779cb66568de74

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
    - pyqt <5.13
    - qtpy >=1.5.0
    - qtawesome >=1.0.2
  run:
    - ffmpeg
    - pyqt <5.13
    - python
    - qtawesome >=1.0.2
    - qtpy >=1.5.0

test:
  imports:
    - QScreenCast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/QScreenCast
  summary: A no-nonsense screen-caster behind a QToolButton.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
