{% set name = "QScreenCast" %}
{% set version = "0.1.35" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QScreenCast-{{ version }}.tar.gz
  sha256: bc8c27489acb3aee525e96f690e8dc27e52e6ddb1473e051627bf0947e9f4b1a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
    - pyqt <5.13
    - qtpy >=1.5.0
    - qtawesome >=1.0.2
  run:
    - ffmpeg
    - pyqt <5.13
    - python
    - qtawesome >=1.0.2
    - qtpy >=1.5.0

test:
  imports:
    - QScreenCast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/QScreenCast
  summary: A no-nonsense screen-caster behind a QToolButton.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
