{% set name = "QScreenCast" %}
{% set version = "0.1.41" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QScreenCast-{{ version }}.tar.gz
  sha256: a00847072b1a77a903d13d1572100fa3ac91d5665bac87d93df363a7b038cd6d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
#  skip: true  # [not win]

requirements:
  host:
    - pip
    - python =3.9
#    - pyqt >=5.15.4
#    - qtpy >=2.0.1
#    - qtawesome>=1.1.1
  run:
    - ffmpeg
    - pyqt >=5.15.4
    - python 
    - qtawesome >=1.1.1
    - qtpy >=2.0.1

test:
  imports:
    - QScreenCast
  commands:
#    - pip check
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/QScreenCast
  summary: A no-nonsense screen-caster behind a QToolButton.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
